openapi: 3.0.3
info:
  title: Backplane-API
  description: API For backplane
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Backplane API hosted URL
 paths:
  /test:
    get:
      summary: Returns a list of test resourses.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of test resourses
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string